events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        servername ;

        location = / {
            default_type text/html;
            alias /etc/nginx/maicha.html;
        }

        location /health { proxy_pass http://fastapi:8000/; }
        location /agents { proxy_pass http://fastapi:8000/; }
        location /chat { proxy_pass http://fastapi:8000/; }
        location /menu { proxy_pass http://fastapi:8000/; }
        location /properties { proxy_pass http://fastapi:8000/; }
        location /orders { proxy_pass http://fastapi:8000/; }
        location /conversations { proxy_pass http://fastapi:8000/; }
        location /events { proxy_pass http://fastapi:8000/; }
        location /stats { proxy_pass http://fastapi:8000/; }
        location /docs { proxy_pass http://fastapi:8000/; }
        location /openapi.json { proxy_pass http://fastapi:8000/; }
    }
}
